# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrate_position.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calibrate_Position(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.bttn_BACK_MAIN = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_BACK_MAIN.setGeometry(QtCore.QRect(620, 430, 171, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_BACK_MAIN.setFont(font)
        self.bttn_BACK_MAIN.setObjectName("bttn_BACK_MAIN")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 321, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.lcd_position = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_position.setObjectName("lcd_position")
        self.horizontalLayout.addWidget(self.lcd_position)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_2.addWidget(self.label_6)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.lcd_MAX_WEIGHT = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_MAX_WEIGHT.setObjectName("lcd_MAX_WEIGHT")
        self.horizontalLayout_2.addWidget(self.lcd_MAX_WEIGHT)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_3.addWidget(self.label_9)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.lcd_CURRENT_WEIGHT = QtWidgets.QLCDNumber(self.layoutWidget)
        self.lcd_CURRENT_WEIGHT.setObjectName("lcd_CURRENT_WEIGHT")
        self.horizontalLayout_3.addWidget(self.lcd_CURRENT_WEIGHT)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(370, 340, 421, 84))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bttn_GO_TOP = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.bttn_GO_TOP.setFont(font)
        self.bttn_GO_TOP.setObjectName("bttn_GO_TOP")
        self.horizontalLayout_4.addWidget(self.bttn_GO_TOP)
        self.bttn_SET_TOP = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.bttn_SET_TOP.setFont(font)
        self.bttn_SET_TOP.setObjectName("bttn_SET_TOP")
        self.horizontalLayout_4.addWidget(self.bttn_SET_TOP)
        self.lb_TOP_SET = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_TOP_SET.setFont(font)
        self.lb_TOP_SET.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_TOP_SET.setObjectName("lb_TOP_SET")
        self.horizontalLayout_4.addWidget(self.lb_TOP_SET)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.bttn_GO_BOTTOM = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.bttn_GO_BOTTOM.setFont(font)
        self.bttn_GO_BOTTOM.setObjectName("bttn_GO_BOTTOM")
        self.horizontalLayout_5.addWidget(self.bttn_GO_BOTTOM)
        self.bttn_SET_BOTTOM = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setItalic(False)
        self.bttn_SET_BOTTOM.setFont(font)
        self.bttn_SET_BOTTOM.setObjectName("bttn_SET_BOTTOM")
        self.horizontalLayout_5.addWidget(self.bttn_SET_BOTTOM)
        self.lb_BOTTOM_SET = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_BOTTOM_SET.setFont(font)
        self.lb_BOTTOM_SET.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_BOTTOM_SET.setObjectName("lb_BOTTOM_SET")
        self.horizontalLayout_5.addWidget(self.lb_BOTTOM_SET)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(0, 250, 126, 125))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rb_FAST = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rb_FAST.setFont(font)
        self.rb_FAST.setObjectName("rb_FAST")
        self.verticalLayout_3.addWidget(self.rb_FAST)
        self.rb_NORMAL = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rb_NORMAL.setFont(font)
        self.rb_NORMAL.setObjectName("rb_NORMAL")
        self.verticalLayout_3.addWidget(self.rb_NORMAL)
        self.rb_SLOW = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.rb_SLOW.setFont(font)
        self.rb_SLOW.setObjectName("rb_SLOW")
        self.verticalLayout_3.addWidget(self.rb_SLOW)
        self.layoutWidget3 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget3.setGeometry(QtCore.QRect(150, 240, 185, 141))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.bttn_START = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_START.setFont(font)
        self.bttn_START.setObjectName("bttn_START")
        self.verticalLayout_4.addWidget(self.bttn_START)
        self.bttn_STOP = QtWidgets.QPushButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_STOP.setFont(font)
        self.bttn_STOP.setObjectName("bttn_STOP")
        self.verticalLayout_4.addWidget(self.bttn_STOP)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.radioButton_4 = QtWidgets.QRadioButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_4.setFont(font)
        self.radioButton_4.setObjectName("radioButton_4")
        self.horizontalLayout_6.addWidget(self.radioButton_4)
        self.radioButton_5 = QtWidgets.QRadioButton(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_5.setFont(font)
        self.radioButton_5.setObjectName("radioButton_5")
        self.horizontalLayout_6.addWidget(self.radioButton_5)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.sld_DUTYCYCLE = QtWidgets.QSlider(self.centralwidget)
        self.sld_DUTYCYCLE.setGeometry(QtCore.QRect(10, 400, 321, 20))
        self.sld_DUTYCYCLE.setOrientation(QtCore.Qt.Horizontal)
        self.sld_DUTYCYCLE.setObjectName("sld_DUTYCYCLE")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 430, 31, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 430, 51, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.gv_MotorPosition = QtWidgets.QGraphicsView(self.centralwidget)
        self.gv_MotorPosition.setGeometry(QtCore.QRect(355, 11, 431, 301))
        self.gv_MotorPosition.setObjectName("gv_MotorPosition")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bttn_BACK_MAIN.setText(_translate("MainWindow", "Main Menu"))
        self.label_5.setText(_translate("MainWindow", "Position"))
        self.label_6.setText(_translate("MainWindow", "Max Weight"))
        self.label_9.setText(_translate("MainWindow", "Current Weight"))
        self.bttn_GO_TOP.setText(_translate("MainWindow", "Go Top"))
        self.bttn_SET_TOP.setText(_translate("MainWindow", "Set Top"))
        self.lb_TOP_SET.setText(_translate("MainWindow", "Not Set "))
        self.bttn_GO_BOTTOM.setText(_translate("MainWindow", "Go Bottom"))
        self.bttn_SET_BOTTOM.setText(_translate("MainWindow", "Set Bottom"))
        self.lb_BOTTOM_SET.setText(_translate("MainWindow", "Not Set "))
        self.rb_FAST.setText(_translate("MainWindow", "Fast"))
        self.rb_NORMAL.setText(_translate("MainWindow", "Normal"))
        self.rb_SLOW.setText(_translate("MainWindow", "Slow "))
        self.bttn_START.setText(_translate("MainWindow", "Start"))
        self.bttn_STOP.setText(_translate("MainWindow", "Stop"))
        self.radioButton_4.setText(_translate("MainWindow", "FWD"))
        self.radioButton_5.setText(_translate("MainWindow", "REV"))
        self.label.setText(_translate("MainWindow", "0%"))
        self.label_2.setText(_translate("MainWindow", "100%"))

