# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibrate_loadcell.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Calibrate_LoadCell(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(30, 50, 271, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.bttn_BACK_MAIN = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_BACK_MAIN.setGeometry(QtCore.QRect(620, 430, 171, 44))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_BACK_MAIN.setFont(font)
        self.bttn_BACK_MAIN.setObjectName("bttn_BACK_MAIN")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 50, 311, 131))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bttn_CAPTURE_ZERO = QtWidgets.QPushButton(self.widget)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_CAPTURE_ZERO.setFont(font)
        self.bttn_CAPTURE_ZERO.setObjectName("bttn_CAPTURE_ZERO")
        self.verticalLayout.addWidget(self.bttn_CAPTURE_ZERO)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        self.tb_SPAN = QtWidgets.QLineEdit(self.widget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.tb_SPAN.setFont(font)
        self.tb_SPAN.setObjectName("tb_SPAN")
        self.horizontalLayout_3.addWidget(self.tb_SPAN)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.splitter = QtWidgets.QSplitter(self.widget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.bttn_SET_SPAN = QtWidgets.QPushButton(self.splitter)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_SET_SPAN.setFont(font)
        self.bttn_SET_SPAN.setObjectName("bttn_SET_SPAN")
        self.verticalLayout.addWidget(self.splitter)
        self.widget1 = QtWidgets.QWidget(self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(430, 30, 301, 188))
        self.widget1.setObjectName("widget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_4.addWidget(self.label_7)
        self.lcd_TARE = QtWidgets.QLCDNumber(self.widget1)
        self.lcd_TARE.setObjectName("lcd_TARE")
        self.horizontalLayout_4.addWidget(self.lcd_TARE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.bttn_SYSTEM_ZERO = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_SYSTEM_ZERO.setFont(font)
        self.bttn_SYSTEM_ZERO.setObjectName("bttn_SYSTEM_ZERO")
        self.verticalLayout_2.addWidget(self.bttn_SYSTEM_ZERO)
        self.bttn_RESET_ZERO = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_RESET_ZERO.setFont(font)
        self.bttn_RESET_ZERO.setObjectName("bttn_RESET_ZERO")
        self.verticalLayout_2.addWidget(self.bttn_RESET_ZERO)
        self.bttn_TARE_SCALE = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_TARE_SCALE.setFont(font)
        self.bttn_TARE_SCALE.setObjectName("bttn_TARE_SCALE")
        self.verticalLayout_2.addWidget(self.bttn_TARE_SCALE)
        self.bttn_RESET_TARE = QtWidgets.QPushButton(self.widget1)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_RESET_TARE.setFont(font)
        self.bttn_RESET_TARE.setObjectName("bttn_RESET_TARE")
        self.verticalLayout_2.addWidget(self.bttn_RESET_TARE)
        self.widget2 = QtWidgets.QWidget(self.centralwidget)
        self.widget2.setGeometry(QtCore.QRect(10, 220, 311, 76))
        self.widget2.setObjectName("widget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.widget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.bttn_STAGE_UP_SINGLE = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_STAGE_UP_SINGLE.setFont(font)
        self.bttn_STAGE_UP_SINGLE.setObjectName("bttn_STAGE_UP_SINGLE")
        self.verticalLayout_3.addWidget(self.bttn_STAGE_UP_SINGLE)
        self.bttn_STAGE_DOWN_SINGLE = QtWidgets.QPushButton(self.widget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_STAGE_DOWN_SINGLE.setFont(font)
        self.bttn_STAGE_DOWN_SINGLE.setObjectName("bttn_STAGE_DOWN_SINGLE")
        self.verticalLayout_3.addWidget(self.bttn_STAGE_DOWN_SINGLE)
        self.widget3 = QtWidgets.QWidget(self.centralwidget)
        self.widget3.setGeometry(QtCore.QRect(10, 340, 311, 112))
        self.widget3.setObjectName("widget3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.widget3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_2 = QtWidgets.QLabel(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_6.addWidget(self.label_2)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.tb_NUMOFSTEPS = QtWidgets.QLineEdit(self.widget3)
        self.tb_NUMOFSTEPS.setObjectName("tb_NUMOFSTEPS")
        self.horizontalLayout_6.addWidget(self.tb_NUMOFSTEPS)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.bttn_STAGE_UP_MULTI = QtWidgets.QPushButton(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_STAGE_UP_MULTI.setFont(font)
        self.bttn_STAGE_UP_MULTI.setObjectName("bttn_STAGE_UP_MULTI")
        self.verticalLayout_4.addWidget(self.bttn_STAGE_UP_MULTI)
        self.bttn_STAGE_DOWN_MULTI = QtWidgets.QPushButton(self.widget3)
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setItalic(False)
        self.bttn_STAGE_DOWN_MULTI.setFont(font)
        self.bttn_STAGE_DOWN_MULTI.setObjectName("bttn_STAGE_DOWN_MULTI")
        self.verticalLayout_4.addWidget(self.bttn_STAGE_DOWN_MULTI)
        self.widget4 = QtWidgets.QWidget(self.centralwidget)
        self.widget4.setGeometry(QtCore.QRect(360, 330, 391, 84))
        self.widget4.setObjectName("widget4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.bttn_GO_TOP = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.bttn_GO_TOP.setFont(font)
        self.bttn_GO_TOP.setObjectName("bttn_GO_TOP")
        self.horizontalLayout.addWidget(self.bttn_GO_TOP)
        self.lb_TOP_SET = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_TOP_SET.setFont(font)
        self.lb_TOP_SET.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_TOP_SET.setObjectName("lb_TOP_SET")
        self.horizontalLayout.addWidget(self.lb_TOP_SET)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bttn_GO_BOTTOM = QtWidgets.QPushButton(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.bttn_GO_BOTTOM.setFont(font)
        self.bttn_GO_BOTTOM.setObjectName("bttn_GO_BOTTOM")
        self.horizontalLayout_2.addWidget(self.bttn_GO_BOTTOM)
        self.lb_BOTTOM_SET = QtWidgets.QLabel(self.widget4)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.lb_BOTTOM_SET.setFont(font)
        self.lb_BOTTOM_SET.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_BOTTOM_SET.setObjectName("lb_BOTTOM_SET")
        self.horizontalLayout_2.addWidget(self.lb_BOTTOM_SET)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.widget5 = QtWidgets.QWidget(self.centralwidget)
        self.widget5.setGeometry(QtCore.QRect(390, 240, 331, 70))
        self.widget5.setObjectName("widget5")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.widget5)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lcd_WEIGHT = QtWidgets.QLCDNumber(self.widget5)
        self.lcd_WEIGHT.setObjectName("lcd_WEIGHT")
        self.horizontalLayout_5.addWidget(self.lcd_WEIGHT)
        self.verticalLayout_6.addLayout(self.horizontalLayout_5)
        self.bttn_POLL_SENSORS = QtWidgets.QPushButton(self.widget5)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.bttn_POLL_SENSORS.setFont(font)
        self.bttn_POLL_SENSORS.setObjectName("bttn_POLL_SENSORS")
        self.verticalLayout_6.addWidget(self.bttn_POLL_SENSORS)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bttn_BACK_MAIN.setText(_translate("MainWindow", "Main Menu"))
        self.bttn_CAPTURE_ZERO.setText(_translate("MainWindow", "Capture Zero"))
        self.label.setText(_translate("MainWindow", "Span"))
        self.bttn_SET_SPAN.setText(_translate("MainWindow", "Set Span"))
        self.label_7.setText(_translate("MainWindow", "Tare"))
        self.bttn_SYSTEM_ZERO.setText(_translate("MainWindow", "Set System Zero"))
        self.bttn_RESET_ZERO.setText(_translate("MainWindow", "Reset Zero"))
        self.bttn_TARE_SCALE.setText(_translate("MainWindow", "Tare Scale"))
        self.bttn_RESET_TARE.setText(_translate("MainWindow", "Reset Tare"))
        self.bttn_STAGE_UP_SINGLE.setText(_translate("MainWindow", "Stage Up Single Step"))
        self.bttn_STAGE_DOWN_SINGLE.setText(_translate("MainWindow", "Stage Down Single Step"))
        self.label_2.setText(_translate("MainWindow", "Steps"))
        self.bttn_STAGE_UP_MULTI.setText(_translate("MainWindow", "Stage Up Multiple"))
        self.bttn_STAGE_DOWN_MULTI.setText(_translate("MainWindow", "Stage Down Multiple"))
        self.bttn_GO_TOP.setText(_translate("MainWindow", "Go Top"))
        self.lb_TOP_SET.setText(_translate("MainWindow", "Not Set "))
        self.bttn_GO_BOTTOM.setText(_translate("MainWindow", "Go Bottom"))
        self.lb_BOTTOM_SET.setText(_translate("MainWindow", "Not Set "))
        self.label_6.setText(_translate("MainWindow", "Weight"))
        self.bttn_POLL_SENSORS.setText(_translate("MainWindow", "Poll Load Cell"))

