# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_ui.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 480)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 10, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(26)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.bttn_SINGLE_PULSE = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_SINGLE_PULSE.setGeometry(QtCore.QRect(320, 340, 210, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_SINGLE_PULSE.setFont(font)
        self.bttn_SINGLE_PULSE.setObjectName("bttn_SINGLE_PULSE")
        self.bttn_TIME_LAPSE = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_TIME_LAPSE.setGeometry(QtCore.QRect(550, 340, 210, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_TIME_LAPSE.setFont(font)
        self.bttn_TIME_LAPSE.setObjectName("bttn_TIME_LAPSE")
        self.bttn_QUIT = QtWidgets.QPushButton(self.centralwidget)
        self.bttn_QUIT.setGeometry(QtCore.QRect(320, 390, 441, 36))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_QUIT.setFont(font)
        self.bttn_QUIT.setObjectName("bttn_QUIT")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 100, 212, 331))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.bttn_EM100 = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_EM100.setFont(font)
        self.bttn_EM100.setObjectName("bttn_EM100")
        self.verticalLayout.addWidget(self.bttn_EM100)
        self.bttn_CALIBRATE_LC = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_CALIBRATE_LC.setFont(font)
        self.bttn_CALIBRATE_LC.setObjectName("bttn_CALIBRATE_LC")
        self.verticalLayout.addWidget(self.bttn_CALIBRATE_LC)
        self.bttn_CALIBRATE_P = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_CALIBRATE_P.setFont(font)
        self.bttn_CALIBRATE_P.setObjectName("bttn_CALIBRATE_P")
        self.verticalLayout.addWidget(self.bttn_CALIBRATE_P)
        self.bttn_CALIBRATE_C = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_CALIBRATE_C.setFont(font)
        self.bttn_CALIBRATE_C.setObjectName("bttn_CALIBRATE_C")
        self.verticalLayout.addWidget(self.bttn_CALIBRATE_C)
        self.bttn_CALIBRATE_W = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.bttn_CALIBRATE_W.setFont(font)
        self.bttn_CALIBRATE_W.setObjectName("bttn_CALIBRATE_W")
        self.verticalLayout.addWidget(self.bttn_CALIBRATE_W)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(350, 190, 160, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.rb_IMPULSE = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rb_IMPULSE.setFont(font)
        self.rb_IMPULSE.setObjectName("rb_IMPULSE")
        self.verticalLayout_2.addWidget(self.rb_IMPULSE)
        self.rb_SINESOIDAL = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rb_SINESOIDAL.setFont(font)
        self.rb_SINESOIDAL.setObjectName("rb_SINESOIDAL")
        self.verticalLayout_2.addWidget(self.rb_SINESOIDAL)
        self.rb_SQUARE_WAVE = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rb_SQUARE_WAVE.setFont(font)
        self.rb_SQUARE_WAVE.setObjectName("rb_SQUARE_WAVE")
        self.verticalLayout_2.addWidget(self.rb_SQUARE_WAVE)
        self.layoutWidget2 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget2.setGeometry(QtCore.QRect(560, 190, 173, 131))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.rb_FREE_SPIN = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rb_FREE_SPIN.setFont(font)
        self.rb_FREE_SPIN.setObjectName("rb_FREE_SPIN")
        self.verticalLayout_3.addWidget(self.rb_FREE_SPIN)
        self.rb_STRAIN_CONTROL = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rb_STRAIN_CONTROL.setFont(font)
        self.rb_STRAIN_CONTROL.setObjectName("rb_STRAIN_CONTROL")
        self.verticalLayout_3.addWidget(self.rb_STRAIN_CONTROL)
        self.rb_LOAD_CONTROL = QtWidgets.QRadioButton(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.rb_LOAD_CONTROL.setFont(font)
        self.rb_LOAD_CONTROL.setObjectName("rb_LOAD_CONTROL")
        self.verticalLayout_3.addWidget(self.rb_LOAD_CONTROL)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.bttn_QUIT.clicked.connect(MainWindow.close)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Main Menu"))
        self.bttn_SINGLE_PULSE.setText(_translate("MainWindow", "Single Pulse"))
        self.bttn_TIME_LAPSE.setText(_translate("MainWindow", "Time Lapse"))
        self.bttn_QUIT.setText(_translate("MainWindow", "Quit"))
        self.bttn_EM100.setText(_translate("MainWindow", "EM100 Terminal"))
        self.bttn_CALIBRATE_LC.setText(_translate("MainWindow", "Calibrate Load Cell"))
        self.bttn_CALIBRATE_P.setText(_translate("MainWindow", "Calibrate Position"))
        self.bttn_CALIBRATE_C.setText(_translate("MainWindow", "Calibrate Camera"))
        self.bttn_CALIBRATE_W.setText(_translate("MainWindow", "Capture Weight"))
        self.rb_IMPULSE.setText(_translate("MainWindow", "Impulse"))
        self.rb_SINESOIDAL.setText(_translate("MainWindow", "Sinesoidal"))
        self.rb_SQUARE_WAVE.setText(_translate("MainWindow", "Square Wave"))
        self.rb_FREE_SPIN.setText(_translate("MainWindow", "Free Spin"))
        self.rb_STRAIN_CONTROL.setText(_translate("MainWindow", "Strain Control"))
        self.rb_LOAD_CONTROL.setText(_translate("MainWindow", "Load Control"))

